// ============================================================================
// Database Row Type Definitions
// @lm-vision/supabase-client — packages/supabase-client/src/types/database.ts
// ============================================================================
// PURPOSE:
//   Hand-maintained TypeScript types mirroring the PostgreSQL database schema
//   defined in supabase/migrations/. These types represent raw database rows.
//
// IMPORTANT — SCHEMA DRIFT DETECTION:
//   These types are hand-maintained and NOT auto-generated by Supabase codegen.
//   This avoids coupling the domain layer to Supabase's generated output.
//
//   However, since they are not auto-generated, they can drift from the actual
//   schema. To detect important drift:
//     1. Run the drift-check test in tests/phase2-database.test.ts
//     2. When modifying migrations, update corresponding types here
//     3. The CI pipeline (Phase 17 QA) should run supabase db diff to catch drift
//
// NAMING CONVENTION:
//   - DatabaseRow<TableName>: represents a complete row as returned by SELECT *
//   - DatabaseInsert<TableName>: represents the INSERT payload (id/created_at may be optional)
//   - All timestamps are ISO strings (Supabase returns timestamptz as ISO string)
//   - All UUIDs are plain strings
// ============================================================================

// ============================================================================
// roles
// ============================================================================
export interface DatabaseRowRole {
  id: string;
  name: 'INSPECTOR' | 'SUPERVISOR' | 'ADMIN' | 'AUDITOR';
  description: string;
  created_at: string;
}

export type DatabaseInsertRole = Omit<DatabaseRowRole, 'created_at'> & {
  created_at?: string;
};

// ============================================================================
// users
// ============================================================================
export interface DatabaseRowUser {
  id: string;
  role_id: string;
  full_name: string;
  employee_code: string | null;
  phone: string | null;
  is_active: boolean;
  badge_number: string | null;
  designation: string | null;
  jurisdiction_zone: string | null;
  jurisdiction_state: string | null;
  office_address: string | null;
  created_at: string;
  updated_at: string;
  last_login_at: string | null;
}

export type DatabaseInsertUser = Omit<DatabaseRowUser, 'created_at' | 'updated_at'> & {
  created_at?: string;
  updated_at?: string;
};

// ============================================================================
// manufacturers
// ============================================================================
export interface DatabaseRowManufacturer {
  id: string;
  legal_name: string;
  aliases: string[];
  contact_metadata: Record<string, unknown>;
  created_at: string;
  updated_at: string;
}

export type DatabaseInsertManufacturer = Omit<DatabaseRowManufacturer, 'id' | 'created_at' | 'updated_at'> & {
  id?: string;
  created_at?: string;
  updated_at?: string;
};

// ============================================================================
// products
// ============================================================================
export interface DatabaseRowProduct {
  id: string;
  manufacturer_id: string;
  name: string;
  category: string;
  package_type: string | null;
  metadata: Record<string, unknown>;
  created_at: string;
  updated_at: string;
}

export type DatabaseInsertProduct = Omit<DatabaseRowProduct, 'id' | 'created_at' | 'updated_at'> & {
  id?: string;
  created_at?: string;
  updated_at?: string;
};

// ============================================================================
// inspections
// ============================================================================
export interface DatabaseRowInspection {
  id: string;
  inspector_id: string;
  product_id: string | null;
  status: string;
  source_type: 'PHYSICAL' | 'ECOMMERCE' | 'HYBRID';
  location_metadata: Record<string, unknown>;
  started_at: string;
  completed_at: string | null;
  rule_version_context: Record<string, unknown>;
  created_at: string;
  updated_at: string;
  sync_version?: number;
  last_synced_at?: string | null;
  local_updated_at?: string | null;
  sync_status?: string;
  sync_error?: string | null;
  conflict_state?: Record<string, unknown> | null;
}

export type DatabaseInsertInspection = Omit<DatabaseRowInspection, 'id' | 'created_at' | 'updated_at'> & {
  id?: string;
  status?: string;
  created_at?: string;
  updated_at?: string;
};

// ============================================================================
// inspection_images
// ============================================================================
export interface DatabaseRowInspectionImage {
  id: string;
  inspection_id: string;
  storage_path: string;
  sha256: string;
  mime_type: string;
  width: number | null;
  height: number | null;
  surface: string | null;
  capture_metadata: Record<string, unknown>;
  quality_score: number | null;
  created_at: string;
  sync_status?: string;
  upload_error?: string | null;
}

export type DatabaseInsertInspectionImage = Omit<DatabaseRowInspectionImage, 'id' | 'created_at'> & {
  id?: string;
  created_at?: string;
};

// ============================================================================
// ai_analyses
// ============================================================================
export interface DatabaseRowAiAnalysis {
  id: string;
  inspection_id: string;
  provider: 'GEMINI' | 'OPENAI' | 'MOCK' | 'LOCAL_OCR' | 'HYBRID';
  model: string;
  schema_version: string;
  status: string;
  confidence: number | null;
  payload: Record<string, unknown>;
  created_at: string;
}

export type DatabaseInsertAiAnalysis = Omit<DatabaseRowAiAnalysis, 'id' | 'created_at'> & {
  id?: string;
  status?: string;
  created_at?: string;
};

// ============================================================================
// declarations
// ============================================================================
export interface DatabaseRowDeclaration {
  id: string;
  inspection_id: string;
  ai_analysis_id: string;
  field_name: string;
  raw_value: string | null;
  normalized_value: Record<string, unknown>;
  confidence: number | null;
  verification_status: 'UNVERIFIED' | 'VERIFIED' | 'REJECTED';
  evidence_refs: string[];
  created_at: string;
  updated_at: string;
}

export type DatabaseInsertDeclaration = Omit<DatabaseRowDeclaration, 'id' | 'created_at' | 'updated_at'> & {
  id?: string;
  verification_status?: 'UNVERIFIED' | 'VERIFIED' | 'REJECTED';
  created_at?: string;
  updated_at?: string;
};

// ============================================================================
// rules
// ============================================================================
export interface DatabaseRowRule {
  id: string;
  rule_number: string | null;
  sub_rule: string | null;
  title: string;
  category: string;
  created_at: string;
}

// ============================================================================
// rule_versions
// ============================================================================
export interface DatabaseRowRuleVersion {
  id: string;
  rule_id: string;
  version: string;
  applicability: Record<string, unknown>;
  conditions: Record<string, unknown>;
  requirement: Record<string, unknown>;
  validation_type: string | null;
  threshold: Record<string, unknown> | null;
  exceptions: Record<string, unknown> | null;
  effective_from: string | null;
  effective_to: string | null;
  source_document: string | null;
  source_page: string | null;
  approval_status: string;
  approved_by: string | null;
  approved_at: string | null;
  created_at: string;
}

// ============================================================================
// findings
// ============================================================================
export interface DatabaseRowFinding {
  id: string;
  inspection_id: string;
  rule_version_id: string | null;
  finding_type: string;
  status: string;
  title: string;
  explanation: string;
  confidence: number | null;
  human_review_required: boolean;
  created_at: string;
  updated_at: string;
}

// ============================================================================
// evidence
// ============================================================================
export interface DatabaseRowEvidence {
  id: string;
  inspection_id: string;
  finding_id: string | null;
  evidence_type: string;
  storage_path: string | null;
  sha256: string | null;
  source_reference: Record<string, unknown>;
  captured_at: string | null;
  captured_by: string | null;
  verified_by: string | null;
  verified_at: string | null;
  status: string;
  created_at: string;
}

// ============================================================================
// inspector_decisions
// ============================================================================
export interface DatabaseRowInspectorDecision {
  id: string;
  inspection_id: string;
  inspector_id: string;
  decision: string;
  comments: string;
  decided_at: string;
}

// ============================================================================
// ecommerce_listings
// ============================================================================
export interface DatabaseRowEcommerceListing {
  id: string;
  inspection_id: string;
  source_url: string | null;
  captured_at: string;
  merchant_name: string | null;
  fields: Record<string, unknown>;
  screenshot_evidence_id: string | null;
  analysis_status: string;
}

// ============================================================================
// cross_source_comparisons
// ============================================================================
export interface DatabaseRowCrossSourceComparison {
  id: string;
  inspection_id: string;
  listing_id: string;
  comparison: unknown[];
  status: string;
  created_at: string;
}

// ============================================================================
// reports
// ============================================================================
export interface DatabaseRowReport {
  id: string;
  inspection_id: string;
  format: 'PDF' | 'HTML' | 'JSON';
  storage_path: string | null;
  sha256: string | null;
  generated_by: string;
  generated_at: string;
}

// ============================================================================
// audit_logs
// ============================================================================
export interface DatabaseRowAuditLog {
  id: string;
  actor_user_id: string | null;
  action: string;
  entity_type: string;
  entity_id: string;
  before_data: Record<string, unknown> | null;
  after_data: Record<string, unknown> | null;
  metadata: Record<string, unknown>;
  created_at: string;
}

export type DatabaseInsertAuditLog = Omit<DatabaseRowAuditLog, 'id' | 'created_at'> & {
  id?: string;
  created_at?: string;
};

// ============================================================================
// Schema Drift Detection Helper
// ============================================================================
// This type validates that DatabaseRowUser has the expected shape.
// If the migration changes a column, update this type AND the check test.
// See tests/phase2-database.test.ts for the drift check tests.
export const SCHEMA_VERSION = '2.0.0' as const;

/**
 * Known required columns per table — used in drift detection tests.
 * When you add or rename a column in migrations, update this map.
 */
export const EXPECTED_TABLE_COLUMNS: Record<string, readonly string[]> = {
  roles: ['id', 'name', 'description', 'created_at'],
  users: [
    'id', 'role_id', 'full_name', 'employee_code', 'phone', 'is_active',
    'badge_number', 'designation', 'jurisdiction_zone', 'jurisdiction_state',
    'office_address', 'created_at', 'updated_at', 'last_login_at',
  ],
  manufacturers: ['id', 'legal_name', 'aliases', 'contact_metadata', 'created_at', 'updated_at'],
  products: ['id', 'manufacturer_id', 'name', 'category', 'package_type', 'metadata', 'created_at', 'updated_at'],
  inspections: [
    'id', 'inspector_id', 'product_id', 'status', 'source_type',
    'location_metadata', 'started_at', 'completed_at', 'rule_version_context',
    'created_at', 'updated_at',
  ],
  inspection_images: [
    'id', 'inspection_id', 'storage_path', 'sha256', 'mime_type',
    'width', 'height', 'surface', 'capture_metadata', 'quality_score', 'created_at',
  ],
  ai_analyses: ['id', 'inspection_id', 'provider', 'model', 'schema_version', 'status', 'confidence', 'payload', 'created_at'],
  declarations: [
    'id', 'inspection_id', 'ai_analysis_id', 'field_name', 'raw_value',
    'normalized_value', 'confidence', 'verification_status', 'evidence_refs',
    'created_at', 'updated_at',
  ],
  rules: ['id', 'rule_number', 'sub_rule', 'title', 'category', 'created_at'],
  rule_versions: [
    'id', 'rule_id', 'version', 'applicability', 'conditions', 'requirement',
    'validation_type', 'threshold', 'exceptions', 'effective_from', 'effective_to',
    'source_document', 'source_page', 'approval_status', 'approved_by', 'approved_at', 'created_at',
  ],
  findings: [
    'id', 'inspection_id', 'rule_version_id', 'finding_type', 'status',
    'title', 'explanation', 'confidence', 'human_review_required', 'created_at', 'updated_at',
  ],
  evidence: [
    'id', 'inspection_id', 'finding_id', 'evidence_type', 'storage_path',
    'sha256', 'source_reference', 'captured_at', 'captured_by',
    'verified_by', 'verified_at', 'status', 'created_at',
  ],
  inspector_decisions: ['id', 'inspection_id', 'inspector_id', 'decision', 'comments', 'decided_at'],
  ecommerce_listings: ['id', 'inspection_id', 'source_url', 'captured_at', 'merchant_name', 'fields', 'screenshot_evidence_id', 'analysis_status'],
  cross_source_comparisons: ['id', 'inspection_id', 'listing_id', 'comparison', 'status', 'created_at'],
  reports: ['id', 'inspection_id', 'format', 'storage_path', 'sha256', 'generated_by', 'generated_at'],
  audit_logs: ['id', 'actor_user_id', 'action', 'entity_type', 'entity_id', 'before_data', 'after_data', 'metadata', 'created_at'],
} as const;
