-- =============================================================================
-- Migration 010: Reports
-- LM-Vision Phase 2 — SIH 2026 Problem Statement 26034
-- =============================================================================
-- Depends on: 009_ecommerce_cross_source
-- Schema source: docs/04_DATABASE_DESIGN.md §3 (reports)
-- Report generation: Phase 14 — this migration lays the schema foundation.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- Table: reports
-- Generated inspection reports (PDF/HTML).
-- storage_path references the private Supabase Storage "reports" bucket.
-- sha256 is computed from the report bytes at generation time.
-- -----------------------------------------------------------------------------
create table public.reports (
  id            uuid        not null default gen_random_uuid(),
  inspection_id uuid        not null,
  format        text        not null,
  storage_path  text,
  sha256        text,
  generated_by  uuid        not null,
  generated_at  timestamptz not null default now(),

  constraint reports_pkey primary key (id),

  constraint reports_inspection_fk foreign key (inspection_id)
    references public.inspections(id) on delete restrict on update cascade,

  constraint reports_generated_by_fk foreign key (generated_by)
    references public.users(id) on delete restrict on update cascade,

  -- Format allowlist
  constraint reports_format_valid check (
    format in ('PDF', 'HTML', 'JSON')
  ),

  -- SHA-256: 64 lowercase hex characters when present
  constraint reports_sha256_format check (
    sha256 is null or sha256 ~ '^[0-9a-f]{64}$'
  ),

  -- storage_path required when sha256 is present
  constraint reports_path_hash_consistency check (
    (sha256 is null) = (storage_path is null)
  )
);

comment on table public.reports is
  'Inspection reports in PDF, HTML, or JSON format. '
  'storage_path references the private "reports" bucket — never expose as permanent public URL. '
  'sha256 computed from generated bytes. '
  'Full PDF generation pipeline is Phase 14 — this schema supports that phase. '
  'A report cannot be final if the inspection has unresolved MANUAL_REVIEW findings '
  'without an authorized override — enforced at application layer.';

comment on column public.reports.storage_path is
  'Object key within the "reports" private bucket. '
  'Format: <inspection_id>/report-<uuid>.<format>. '
  'Access via signed URL only.';

comment on column public.reports.sha256 is
  'SHA-256 hex digest of the generated report bytes. '
  'Establishes integrity evidence for the report artifact.';

-- Index: inspection lookup
create index idx_reports_inspection
  on public.reports(inspection_id, generated_at desc);

-- Index: generated_by
create index idx_reports_generated_by
  on public.reports(generated_by, generated_at desc);
